#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'slam','console_scripts','slam_goal'
__requires__ = 'slam'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('slam', 'console_scripts', 'slam_goal')()
    )
