# -*- coding: utf-8 -*-
"""datacrawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ffkAVy7rke8u7zI8tPdV2sMPU-tn8pb
"""
from re import search
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from urllib.request import urlopen
import os
from bs4 import BeautifulSoup as bs
from urllib.parse import quote_plus
import time
import urllib.request
import chromedriver_autoinstaller

# 준비작업 크롬 웹드라이버 연결 #
chrome_ver = chromedriver_autoinstaller.get_chrome_version().split('.')[0]  #크롬드라이버 버전 확인

try:
    driver = webdriver.Chrome(f'./{chrome_ver}/chromedriver.exe')   
except:
    chromedriver_autoinstaller.install(True)
    driver = webdriver.Chrome(f'./{chrome_ver}/chromedriver.exe')

# 이미지가 저장될 디렉토리 생성
def createFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
    except OSError:
        print ('Error: Creating directory. ' +  directory)
# 출처: https://yobbicorgi.tistory.com/29 [상엽’s Python 블로그:티스토리]

# 웹 사이트 접속 #
driver.get('https://www.google.com/imghp?hl=ko')
driver.implicitly_wait(10)

#검색어 입력하기#
search = "포카리스웨트"
createFolder('./'+ search +'_img_download')
Keyword = driver.find_element("name", "q") #인터넷과 다른 부분 selenium 4.3.0버전이라 그럼
Keyword.send_keys(search)
Keyword.send_keys(Keys.RETURN)



# =============================================================================
# 스크롤
# =============================================================================
print(search+' 스크롤 중 .............')
elem =  driver.find_element(By.TAG_NAME,"body")
for i in range(60):
    elem.send_keys(Keys.PAGE_DOWN)
    time.sleep(0.1)
    
try:
    driver.find_element(By.XPATH,'//*[@id="islmp"]/div/div/div/div[1]/div[4]/div[2]/input').click()
    for i in range(60):
        elem.send_keys(Keys.PAGE_DOWN)
        time.sleep(0.1)
except:
    pass


# =============================================================================
# 이미지 개수
# =============================================================================
links=[]
images = driver.find_elements(By.CSS_SELECTOR,"img.rg_i.Q4LuWd")
for image in images:
    if image.get_attribute('src')!=None:
        links.append(image.get_attribute('src'))

print(search+' 찾은 이미지 개수:',len(links))
time.sleep(2)


# =============================================================================
# 이미지 다운로드
# =============================================================================
for k,i in enumerate(links):
    url = i
    start = time.time()
    urllib.request.urlretrieve(url, "./"+search+"_img_download/"+search+"_"+str(k)+".jpg")
    print(str(k+1)+'/'+str(len(links))+' '+search+' 다운로드 중....... Download time : '+str(time.time() - start)[:5]+' 초')
print(search+' ---다운로드 완료---')

driver.close()

