#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'yolov3','console_scripts','yolov3'
__requires__ = 'yolov3'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('yolov3', 'console_scripts', 'yolov3')()
    )
